/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Nguyen Quoc Nhan
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    static MainMenu menu;
    static WindowGame win;
    public Window() {
        this.setLocation(400,150);
        menu = new MainMenu();
        win = new WindowGame();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JLabel();
        instructionsButton = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(578, 440));
        setUndecorated(true);
        getContentPane().setLayout(null);

        playButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });
        getContentPane().add(playButton);
        playButton.setBounds(440, 390, 80, 40);

        instructionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instructionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instructionsButtonMouseClicked(evt);
            }
        });
        getContentPane().add(instructionsButton);
        instructionsButton.setBounds(40, 390, 220, 40);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(548, 0, 32, 30);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 579, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        //menu.setVisible(true);
        win.disAble();
        win = new WindowGame();
        this.setVisible(false);
        try {
            win.main();
        } catch (IOException ex) {
        } catch (InterruptedException ex) {
        } catch (URISyntaxException ex) {
        }
        this.setVisible(false);
    }//GEN-LAST:event_playButtonMouseClicked
    
    private void instructionsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructionsButtonMouseClicked
        // TODO add your handling code here:
      
        String line = new String("");
        BufferedReader in = null;

        try {
            //URL pathFile = this.getClass().getResource("/Huongdan.txt");
            in = new BufferedReader(new FileReader(new File(Paths.get("").toAbsolutePath().toString() + "\\src\\source\\Huongdan.txt")));
        } catch (FileNotFoundException ex) {
        }
        
        String string = "";
        try {
            while((line = in.readLine()) != null)
            {
                string += line;
                string += "\n";
            }
        } catch (IOException ex) {
        }

        JDialog dialog = new JDialog();
        dialog.setTitle("Hướng dẫn");
        dialog.setModal(true);
        dialog.setContentPane(new JScrollPane(new JTextArea(string)));
        dialog.setSize(700, 500);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_instructionsButtonMouseClicked

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        //this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static Window window = new Window();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        window.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel instructionsButton;
    private javax.swing.JLabel playButton;
    // End of variables declaration//GEN-END:variables
}
